### ISSUE TITLE
Dev instructions

### ISSUE THREAD

**Issue by Philmod** [Tstassin/cov19#3]
It would be great to know how to start the page locally in case developers want to contribute.

After reading the `package.json`, I'm guessing: 

```
npm install
npm start
```

But it doesn't launch the page so I must be missing something.

**Comment by Tstassin** [comment]
I just added instructions, the two commands you used are right, I'm used to `gatsby develop` instead of `npm start` on gatsby projects, but in the end they all trigger the same develop mode.. I juste tested a fresh install and dry-run with no issues.
I close this issue considering dev instructions are now provided in the Readme file, don't hesitate to open another or contact me if you're running into install/launch bugs.
